site_name: Portfolio # Название сайта
site_description: "Профессиональное портфолио" # Описание сайта, добавляется в meta-теги

theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: images/logo.jpg # Ссылка на логотип сайта, логотип добавляется в папку `docs/images`
  font:
    text: Merriweather # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
    - scheme: default
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: "Выключить солнышко" # Всплывающий текст-подсказка
      primary: pink # Основной цвет
      accent: purple # Акцентный цвет
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: "Позвать солнышко"
      primary: deep purple
      accent: blue
  features: # настройки функциональностей темы
    - navigation.sections # Добавление разделов верхнего уровня в боковом меню
    - navigation.path # Хлебные крошки
    - navigation.indexes # Корневые страницы разделов (index.md)
    - navigation.tabs # Верхнее меню
    - navigation.tabs.sticky # Фиксация верхнего меню
    - navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    - toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.instant # Быстрая загрузка страниц
    - navigation.top # Кнопка «к началу»
    - search.suggest
    - search.highlight
    - content.code.copy

nav: # Структура сайта (на корневом уровне)
  - Главная страница: index.md
  - "Мой домашний проект":
      - pet-project/notesapp.md
  - "Домашние задания":
      - "Домашнее задание N2": subfolder/subsubfolder/index.md

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


